services:
  maxhax:
    image: mbigras/maxhax:3ff9ba30d51d324374eb2f9213fe134f213f7a11
    restart: always
  cloudflared:
    image: cloudflare/cloudflared:1332-8a9f076a26f7
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN
    env_file: .env
    restart: always
