services:
  maxhax:
    image: mbigras/maxhax:7f68da17200cb71e19b039bf1c16a28ee0e46d9c
    restart: always
  cloudflared:
    image: cloudflare/cloudflared:1332-8a9f076a26f7
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN
    env_file: .env
    restart: always
